# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
  labels:
    {{- include "bloggingapp.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: bloggingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
