# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
spec:
  type: LoadBalancer
  selector:
    app: bloggingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
